name : Vancouver Hikes
brand : Vancouver Hikes
description : Description here!!
keyword : Vancouver Hikes, vancouver hiking
url : http://vancouverhikes.github.io/
email : bryant.n.lim@gmail.com
twitter : VancouverHikes
github : VancouverHikes
author : Bryant Nicholas Lim
analytics : UA-8418273-8
year : 2016
markdown : kramdown
exclude :
  - node_modules
collections:
  trails:
    output: true
    permalink: /trails/:path/
defaults:
  - scope:
      path: "/trails"
      type: trails
    values:
      layout: trails
